### ISSUE TITLE
Загрузка анализа покрытия

### ISSUE THREAD

**Issue by ChALkeR** [ovchinnikov94/js_learn_node#3]
Смотрите ­— сам анализ покрытия работает, но он явно не загружается на coveralls/codecov. Можете выбрать любой из них.
## 

Для работы с codecov достаточно зарегистрировать там проект и сделать следующее:

``` yml
 before_install:
   - npm install -g codecov
 after_success:
   - codecov
```

Для работы codecov c Travis CI токен не нужен. У них это описано в настройках проекта (после подключения).
## 

Для coveralls, аналогично:

``` yml
 before_install:
   - npm install -g coveralls
 after_success:
   - coveralls
```

Но в этом случае вам нужно будет добавить в безопасные переменные окружения переменную CODECOV_TOKEN с API токеном coveralls. Только смотрите — безопасные способы добавить токен — либо через веб-интерфейс (там есть переключатель приватная/публичная переменная), либо в _зашифрованном_ виде в `.travis.yml` (см. https://docs.travis-ci.com/user/encryption-keys/). Общая информация по переменным окружения — https://docs.travis-ci.com/user/environment-variables/.
